//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace tambak.runCmdShellServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="runCmdShellServiceReference.RunCmdShell")]
    public interface RunCmdShell {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:RunCmdShell/runAverageCommand", ReplyAction="urn:RunCmdShell/runAverageCommandResponse")]
        System.IAsyncResult BeginrunAverageCommand(string command, System.AsyncCallback callback, object asyncState);
        
        string EndrunAverageCommand(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RunCmdShellChannel : tambak.runCmdShellServiceReference.RunCmdShell, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class runAverageCommandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public runAverageCommandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RunCmdShellClient : System.ServiceModel.ClientBase<tambak.runCmdShellServiceReference.RunCmdShell>, tambak.runCmdShellServiceReference.RunCmdShell {
        
        private BeginOperationDelegate onBeginrunAverageCommandDelegate;
        
        private EndOperationDelegate onEndrunAverageCommandDelegate;
        
        private System.Threading.SendOrPostCallback onrunAverageCommandCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public RunCmdShellClient() {
        }
        
        public RunCmdShellClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RunCmdShellClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RunCmdShellClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RunCmdShellClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<runAverageCommandCompletedEventArgs> runAverageCommandCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult tambak.runCmdShellServiceReference.RunCmdShell.BeginrunAverageCommand(string command, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginrunAverageCommand(command, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string tambak.runCmdShellServiceReference.RunCmdShell.EndrunAverageCommand(System.IAsyncResult result) {
            return base.Channel.EndrunAverageCommand(result);
        }
        
        private System.IAsyncResult OnBeginrunAverageCommand(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string command = ((string)(inValues[0]));
            return ((tambak.runCmdShellServiceReference.RunCmdShell)(this)).BeginrunAverageCommand(command, callback, asyncState);
        }
        
        private object[] OnEndrunAverageCommand(System.IAsyncResult result) {
            string retVal = ((tambak.runCmdShellServiceReference.RunCmdShell)(this)).EndrunAverageCommand(result);
            return new object[] {
                    retVal};
        }
        
        private void OnrunAverageCommandCompleted(object state) {
            if ((this.runAverageCommandCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.runAverageCommandCompleted(this, new runAverageCommandCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void runAverageCommandAsync(string command) {
            this.runAverageCommandAsync(command, null);
        }
        
        public void runAverageCommandAsync(string command, object userState) {
            if ((this.onBeginrunAverageCommandDelegate == null)) {
                this.onBeginrunAverageCommandDelegate = new BeginOperationDelegate(this.OnBeginrunAverageCommand);
            }
            if ((this.onEndrunAverageCommandDelegate == null)) {
                this.onEndrunAverageCommandDelegate = new EndOperationDelegate(this.OnEndrunAverageCommand);
            }
            if ((this.onrunAverageCommandCompletedDelegate == null)) {
                this.onrunAverageCommandCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnrunAverageCommandCompleted);
            }
            base.InvokeAsync(this.onBeginrunAverageCommandDelegate, new object[] {
                        command}, this.onEndrunAverageCommandDelegate, this.onrunAverageCommandCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override tambak.runCmdShellServiceReference.RunCmdShell CreateChannel() {
            return new RunCmdShellClientChannel(this);
        }
        
        private class RunCmdShellClientChannel : ChannelBase<tambak.runCmdShellServiceReference.RunCmdShell>, tambak.runCmdShellServiceReference.RunCmdShell {
            
            public RunCmdShellClientChannel(System.ServiceModel.ClientBase<tambak.runCmdShellServiceReference.RunCmdShell> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginrunAverageCommand(string command, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = command;
                System.IAsyncResult _result = base.BeginInvoke("runAverageCommand", _args, callback, asyncState);
                return _result;
            }
            
            public string EndrunAverageCommand(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("runAverageCommand", _args, result)));
                return _result;
            }
        }
    }
}
