//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace tambak.getServerTimeReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="getServerTimeReference.GetServerTime")]
    public interface GetServerTime {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetServerTime/getServerTime", ReplyAction="urn:GetServerTime/getServerTimeResponse")]
        System.IAsyncResult BegingetServerTime(System.AsyncCallback callback, object asyncState);
        
        System.DateTime EndgetServerTime(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetServerTimeChannel : tambak.getServerTimeReference.GetServerTime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getServerTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getServerTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.DateTime Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetServerTimeClient : System.ServiceModel.ClientBase<tambak.getServerTimeReference.GetServerTime>, tambak.getServerTimeReference.GetServerTime {
        
        private BeginOperationDelegate onBegingetServerTimeDelegate;
        
        private EndOperationDelegate onEndgetServerTimeDelegate;
        
        private System.Threading.SendOrPostCallback ongetServerTimeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public GetServerTimeClient() {
        }
        
        public GetServerTimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetServerTimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetServerTimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetServerTimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getServerTimeCompletedEventArgs> getServerTimeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult tambak.getServerTimeReference.GetServerTime.BegingetServerTime(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetServerTime(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.DateTime tambak.getServerTimeReference.GetServerTime.EndgetServerTime(System.IAsyncResult result) {
            return base.Channel.EndgetServerTime(result);
        }
        
        private System.IAsyncResult OnBegingetServerTime(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((tambak.getServerTimeReference.GetServerTime)(this)).BegingetServerTime(callback, asyncState);
        }
        
        private object[] OnEndgetServerTime(System.IAsyncResult result) {
            System.DateTime retVal = ((tambak.getServerTimeReference.GetServerTime)(this)).EndgetServerTime(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetServerTimeCompleted(object state) {
            if ((this.getServerTimeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getServerTimeCompleted(this, new getServerTimeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getServerTimeAsync() {
            this.getServerTimeAsync(null);
        }
        
        public void getServerTimeAsync(object userState) {
            if ((this.onBegingetServerTimeDelegate == null)) {
                this.onBegingetServerTimeDelegate = new BeginOperationDelegate(this.OnBegingetServerTime);
            }
            if ((this.onEndgetServerTimeDelegate == null)) {
                this.onEndgetServerTimeDelegate = new EndOperationDelegate(this.OnEndgetServerTime);
            }
            if ((this.ongetServerTimeCompletedDelegate == null)) {
                this.ongetServerTimeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetServerTimeCompleted);
            }
            base.InvokeAsync(this.onBegingetServerTimeDelegate, null, this.onEndgetServerTimeDelegate, this.ongetServerTimeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override tambak.getServerTimeReference.GetServerTime CreateChannel() {
            return new GetServerTimeClientChannel(this);
        }
        
        private class GetServerTimeClientChannel : ChannelBase<tambak.getServerTimeReference.GetServerTime>, tambak.getServerTimeReference.GetServerTime {
            
            public GetServerTimeClientChannel(System.ServiceModel.ClientBase<tambak.getServerTimeReference.GetServerTime> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetServerTime(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getServerTime", _args, callback, asyncState);
                return _result;
            }
            
            public System.DateTime EndgetServerTime(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.DateTime _result = ((System.DateTime)(base.EndInvoke("getServerTime", _args, result)));
                return _result;
            }
        }
    }
}
