//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace tambak.addUsertoRoleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="addUsertoRoleServiceReference.addUsertoRoleSVC")]
    public interface addUsertoRoleSVC {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:addUsertoRoleSVC/addUserToRole", ReplyAction="urn:addUsertoRoleSVC/addUserToRoleResponse")]
        System.IAsyncResult BeginaddUserToRole(string intendedUser, string intendedRole, System.AsyncCallback callback, object asyncState);
        
        void EndaddUserToRole(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface addUsertoRoleSVCChannel : tambak.addUsertoRoleServiceReference.addUsertoRoleSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addUsertoRoleSVCClient : System.ServiceModel.ClientBase<tambak.addUsertoRoleServiceReference.addUsertoRoleSVC>, tambak.addUsertoRoleServiceReference.addUsertoRoleSVC {
        
        private BeginOperationDelegate onBeginaddUserToRoleDelegate;
        
        private EndOperationDelegate onEndaddUserToRoleDelegate;
        
        private System.Threading.SendOrPostCallback onaddUserToRoleCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public addUsertoRoleSVCClient() {
        }
        
        public addUsertoRoleSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public addUsertoRoleSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addUsertoRoleSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addUsertoRoleSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> addUserToRoleCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult tambak.addUsertoRoleServiceReference.addUsertoRoleSVC.BeginaddUserToRole(string intendedUser, string intendedRole, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddUserToRole(intendedUser, intendedRole, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void tambak.addUsertoRoleServiceReference.addUsertoRoleSVC.EndaddUserToRole(System.IAsyncResult result) {
            base.Channel.EndaddUserToRole(result);
        }
        
        private System.IAsyncResult OnBeginaddUserToRole(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string intendedUser = ((string)(inValues[0]));
            string intendedRole = ((string)(inValues[1]));
            return ((tambak.addUsertoRoleServiceReference.addUsertoRoleSVC)(this)).BeginaddUserToRole(intendedUser, intendedRole, callback, asyncState);
        }
        
        private object[] OnEndaddUserToRole(System.IAsyncResult result) {
            ((tambak.addUsertoRoleServiceReference.addUsertoRoleSVC)(this)).EndaddUserToRole(result);
            return null;
        }
        
        private void OnaddUserToRoleCompleted(object state) {
            if ((this.addUserToRoleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addUserToRoleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addUserToRoleAsync(string intendedUser, string intendedRole) {
            this.addUserToRoleAsync(intendedUser, intendedRole, null);
        }
        
        public void addUserToRoleAsync(string intendedUser, string intendedRole, object userState) {
            if ((this.onBeginaddUserToRoleDelegate == null)) {
                this.onBeginaddUserToRoleDelegate = new BeginOperationDelegate(this.OnBeginaddUserToRole);
            }
            if ((this.onEndaddUserToRoleDelegate == null)) {
                this.onEndaddUserToRoleDelegate = new EndOperationDelegate(this.OnEndaddUserToRole);
            }
            if ((this.onaddUserToRoleCompletedDelegate == null)) {
                this.onaddUserToRoleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddUserToRoleCompleted);
            }
            base.InvokeAsync(this.onBeginaddUserToRoleDelegate, new object[] {
                        intendedUser,
                        intendedRole}, this.onEndaddUserToRoleDelegate, this.onaddUserToRoleCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override tambak.addUsertoRoleServiceReference.addUsertoRoleSVC CreateChannel() {
            return new addUsertoRoleSVCClientChannel(this);
        }
        
        private class addUsertoRoleSVCClientChannel : ChannelBase<tambak.addUsertoRoleServiceReference.addUsertoRoleSVC>, tambak.addUsertoRoleServiceReference.addUsertoRoleSVC {
            
            public addUsertoRoleSVCClientChannel(System.ServiceModel.ClientBase<tambak.addUsertoRoleServiceReference.addUsertoRoleSVC> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginaddUserToRole(string intendedUser, string intendedRole, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = intendedUser;
                _args[1] = intendedRole;
                System.IAsyncResult _result = base.BeginInvoke("addUserToRole", _args, callback, asyncState);
                return _result;
            }
            
            public void EndaddUserToRole(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("addUserToRole", _args, result);
            }
        }
    }
}
