//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace tambak.addRoleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="addRoleServiceReference.addRoleService")]
    public interface addRoleService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:addRoleService/addRoles", ReplyAction="urn:addRoleService/addRolesResponse")]
        System.IAsyncResult BeginaddRoles(string intendedRole, System.AsyncCallback callback, object asyncState);
        
        void EndaddRoles(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface addRoleServiceChannel : tambak.addRoleServiceReference.addRoleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addRoleServiceClient : System.ServiceModel.ClientBase<tambak.addRoleServiceReference.addRoleService>, tambak.addRoleServiceReference.addRoleService {
        
        private BeginOperationDelegate onBeginaddRolesDelegate;
        
        private EndOperationDelegate onEndaddRolesDelegate;
        
        private System.Threading.SendOrPostCallback onaddRolesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public addRoleServiceClient() {
        }
        
        public addRoleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public addRoleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addRoleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addRoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> addRolesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult tambak.addRoleServiceReference.addRoleService.BeginaddRoles(string intendedRole, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddRoles(intendedRole, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void tambak.addRoleServiceReference.addRoleService.EndaddRoles(System.IAsyncResult result) {
            base.Channel.EndaddRoles(result);
        }
        
        private System.IAsyncResult OnBeginaddRoles(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string intendedRole = ((string)(inValues[0]));
            return ((tambak.addRoleServiceReference.addRoleService)(this)).BeginaddRoles(intendedRole, callback, asyncState);
        }
        
        private object[] OnEndaddRoles(System.IAsyncResult result) {
            ((tambak.addRoleServiceReference.addRoleService)(this)).EndaddRoles(result);
            return null;
        }
        
        private void OnaddRolesCompleted(object state) {
            if ((this.addRolesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addRolesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addRolesAsync(string intendedRole) {
            this.addRolesAsync(intendedRole, null);
        }
        
        public void addRolesAsync(string intendedRole, object userState) {
            if ((this.onBeginaddRolesDelegate == null)) {
                this.onBeginaddRolesDelegate = new BeginOperationDelegate(this.OnBeginaddRoles);
            }
            if ((this.onEndaddRolesDelegate == null)) {
                this.onEndaddRolesDelegate = new EndOperationDelegate(this.OnEndaddRoles);
            }
            if ((this.onaddRolesCompletedDelegate == null)) {
                this.onaddRolesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddRolesCompleted);
            }
            base.InvokeAsync(this.onBeginaddRolesDelegate, new object[] {
                        intendedRole}, this.onEndaddRolesDelegate, this.onaddRolesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override tambak.addRoleServiceReference.addRoleService CreateChannel() {
            return new addRoleServiceClientChannel(this);
        }
        
        private class addRoleServiceClientChannel : ChannelBase<tambak.addRoleServiceReference.addRoleService>, tambak.addRoleServiceReference.addRoleService {
            
            public addRoleServiceClientChannel(System.ServiceModel.ClientBase<tambak.addRoleServiceReference.addRoleService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginaddRoles(string intendedRole, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = intendedRole;
                System.IAsyncResult _result = base.BeginInvoke("addRoles", _args, callback, asyncState);
                return _result;
            }
            
            public void EndaddRoles(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("addRoles", _args, result);
            }
        }
    }
}
